### ISSUE TITLE
Orbwalker

### ISSUE THREAD

**Issue by plsfixrito** [EloBuddy/EloBuddy.Issues#21]
The current orbwalker is kinda slow in my opinion.

so i think that it can be improved by including ping with the attack timer.

like for example attack delay - mycurrent.ping

so it would be like the old attack earlier X ms but it should be the ping that is used, that will improve the orbwalker attacking speed in my opinion.

i tried using the include ping into calculations but the thing is it only changes a little bit.

for me i play league in around normally 100+ ms so it seems the orbwalker is slow for me.

but in other hand using L$ orbwalker still using my full attack speed when EB dosn't.

**Comment by KoalaHuman** [comment]
@plsfixrito it's already included in calculations, check orbwalker settings -> Attack earlier

**Comment by ghost** [comment]
@KoalaHuman 

> it's already included in calculations, check orbwalker settings -> Include ping tratata

He said:

> i tried using the include ping into calculations but the thing is it only changes a little bit.

@plsfixrito
The reason you cannot use your full attack speed is because the entire elobuddy loader responds per tick and the built in humanizer just returns on **SOME** of the ticks (making you do nothing during those ticks). You cannot disable the built in humanizer as its forced on to prevent getting banned.

(Prevents 1000 calls per second with 0 orb delay.)

This is intentional behavior and I dont think hellsing will be fixing it.

**Comment by KoalaHuman** [comment]
@Alweul I edited right after.

> it's already included in calculations, check orbwalker settings -> Attack earlier

Attack earlier - is exactly what he needs.

**Comment by plsfixrito** [comment]
@KoalaHuman it's not in the orbwalker anymore, there is only include ping into calculations which is not changing much for me.

**Comment by Hellsing** [comment]
Well iCreative must have removed the option then, whyevery, cuz it was just a feature for those who wanted to play around with that value, I might consider readding it, but not right now, sorry, closing this issue.
