### ISSUE TITLE
WndProc messages not blockable

### ISSUE THREAD

**Issue by ghost** [EloBuddy/EloBuddy.Issues#29]
There is no scroll bar on menu overflow for those with no scroll wheel and scrolling in menu changes games camera height.

**Comment by Hellsing** [comment]
There is a scrollbar, it has just been added yesterday, so please update your EloBuddy to see it. Once you've done that, please move your mouse to the right side of the content container and you should see a scrollbar appearing.

According the camera height changes, this issue is already known and will be fixed soon by @finndev, but thanks for reporting anyways!

**Comment by MarioGK** [comment]
Added
