### ISSUE TITLE
EloBuddy.Loader Unhandled Exception

### ISSUE THREAD

**Issue by Griamos** [EloBuddy/EloBuddy.Issues#40]
Help! Everytime i try to install a new addon: [Error](http://i.imgur.com/6P6SNPd.png)

**Comment by ghost** [comment]
WCF Pipe conflict.

@beadwarf Close any program or service that did not come with your computer (and the junkware that came with it) and make sure elobuddy is only open once.

Because: "You can only ever have one WCF service application at a time running which uses a particular base address for its NetNamedPipe endpoints. If you try to start a second one, it fails with AddressAlreadyInUseException because it finds that the name WCF wants to use for the publishing location (derived from the base address) has already been taken by another application."

I also suggest that you ensure that no program is using the port that EB is trying to bind to for this pipe operation. I do NOT know exactly which port it should be for this exact operation but you should be able to find the conflict with TCPView.

@Devs:
I suggest writing a custom handler for this error so users know its a "Connection already in use" error, what port is in use, and what program is using it.
